title: Pattern Cross-Examination for Sexual Assault Cases
description: Tactical courtroom strategies by elite criminal defense lawyers Michael and Alexandra Waddington.
theme: minima
markdown: kramdown
